version: '3.3'

services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend